version: '3.8'
volumes:
  pgdbdata:
  static:
  media:

services:
  pgdb:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - 5433:5432

  admin_movies:
    container_name: admin_movies
    build: ./
    restart: always
    ports:
      - 8000:8000
    env_file:
      - movies_admin/config/.env
    depends_on:
      - pgdb
    volumes:
      - static:/app/static/
      - media:/app/media/

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/var/static/
      - media:/var/media/
    depends_on:
      - admin_movies
    ports:
      - 80:80





